### ISSUE TITLE
Cannot run on Flutter, `dart:cli` not found

### ISSUE THREAD

**Issue by truongsinh** [dart-lang/tflite_native#16]
I have my own `so` file, but compiler still fails.

```
TruongSinhs-8GB:flutter_style_transfer truongsinh$ flutter run
Launching lib/main.dart on Pixel 2 in debug mode...
Initializing gradle...                                              0.8s
Resolving dependencies...                                           2.0s
                                                                        
Compiler message:                                                       
../../../.pub-cache/hosted/pub.dartlang.org/tflite_native-0.2.2/lib/src/bindings/dlib.dart:5:8: Error: Not found: 'dart:cli'
import 'dart:cli' as cli;                                               
       ^                                                                
../../../.pub-cache/hosted/pub.dartlang.org/tflite_native-0.2.2/lib/src/bindings/dlib.dart:49:19: Error: Method not found: 'waitFor'.
    final blobs = cli                                                   
                  ^^^^...                                               
Unhandled exception:                                                    
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Acli; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:578:37)             
<asynchronous suspension>                                               
#2      writeDepfile (package:vm/kernel_front_end.dart:755:21)          
<asynchronous suspension>                                               
#3      FrontendCompiler.compile (package:vm/frontend_server.dart:407:15)
<asynchronous suspension>                                               
#4      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:29:22)
<asynchronous suspension>                                               
#5      starter (package:frontend_server/server.dart:127:27)            
<asynchronous suspension>                                               
#6      main (file:///b/s/w/ir/k/src/flutter/frontend_server/bin/starter.dart:8:30)
<asynchronous suspension>                                               
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
                                                                        
Compiler failed on /Users/truongsinh/Dev/ml/flutter_style_transfer/lib/main.dart
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/usr/local/Cellar/flutter/stable/packages/flutter_tools/gradle/flutter.gradle' line: 765
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebugArm64'.         
> Process 'command '/usr/local/Cellar/flutter/stable/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 8s                                                      
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         9.2s
Gradle task assembleDebug failed with exit code 1
TruongSinhs-8GB:flutter_style_transfer truongsinh$ 
```

**Comment by truongsinh** [comment]
FYI, im working on tflite_native on Flutter Androdi

**Comment by lambdabaa** [comment]
@truongsinh I thought this would be cool to support initially but I think that https://github.com/shaqian/flutter_tflite might be a better bet for you at this time. This library specifically supports desktop use cases right now and we load the tflite dynamic library in a way that's incompatible with Flutter. Flutter looks to have its own asset management system that would likely be a better fit for registering and loading a dynamic library through FFI. @sjindel-google can probably speak more knowledgeably about it.

**Comment by sjindel-google** [comment]
I think https://github.com/flutter/flutter/wiki/Binding-to-native-code-via-FFI might help.

**Comment by truongsinh** [comment]
@lambdabaa I had used https://github.com/shaqian/flutter_tflite that previously, but it uses platform  channel, rather than FFI, which is what i'm interested in.

Actually, I manage to get tflite_native running on Android already (loading lib, loading 2 tflite models, resizing tensors, invoking) https://github.com/truongsinh/tflite_native/tree/working-on-android . Now I'm researching iOS.

**Comment by lambdabaa** [comment]
> @lambdabaa I had used https://github.com/shaqian/flutter_tflite that previously, but it uses platform channel, rather than FFI, which is what i'm interested in.

Out of curiosity why do you want to use FFI instead of Flutter's platform channel? Is it related to model prediction latency?

**Comment by truongsinh** [comment]
> Out of curiosity why do you want to use FFI instead of Flutter's platform channel? Is it related to model prediction latency?

Yes, FFI in theory should have less overhead than platform channel (through JNI), though I'm aware both the tflite C API and Dart FFI now are highly experimental.

A question back to you, is there any reason this repo is using *experimental C API* of tensorflow lite? (or do you use some other communication channel that we can use to discuss further)?

**Comment by lambdabaa** [comment]
> A question back to you, is there any reason this repo is using _experimental C API_ of tensorflow lite? (or do you use some other communication channel that we can use to discuss further)?

There isn't yet a non-experimental, TensorFlow Lite C API. This one https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/c is the only public API. We do need to go ahead and update to the latest version though https://github.com/dart-lang/tflite_native/issues/18.
