### ISSUE TITLE
libtensorflowlite_c-win64.dll does not have any symbols

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/tflite_native#33]
https://github.com/dart-lang/tflite_native/commit/ee967831628b6cf9c239a0d19a5691264060cd4a updated the windows dll, but it does not contain any symbols (verified with Dependency Walker). The dll before that commit does contain symbols.

I uncovered this by pulling in the latest version into the SDK with DEPS and seeing [failures on the Windows analyzer](https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8899452492508702272/+/steps/test_results/0/logs/unapproved_failing_tests__logs_/0).

```
Unhandled exception:
Invalid argument(s): Failed to lookup symbol (127)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:30:29)
#1      TfLiteModelCreateFromFile (package:tflite_native/src/bindings/model.dart:23:10)
#2      TfLiteModelCreateFromFile (package:tflite_native/src/bindings/model.dart:21:51)
```

Symbols in the original dll:

TFL_DeleteInterpreter
TFL_DeleteInterpreterOptions
TFL_DeleteModel
TFL_InterpreterAllocateTensors
TFL_InterpreterGetInputTensor
TFL_InterpreterGetInputTensorCount
TFL_InterpreterGetOutputTensor
TFL_InterpreterGetOutputTensorCount
TFL_InterpreterInvoke
TFL_InterpreterOptionsAddBuiltinOp
TFL_InterpreterOptionsAddCustomOp
TFL_InterpreterOptionsSetErrorReporter
TFL_InterpreterOptionsSetNumThreads
TFL_InterpreterResetVariableTensors
TFL_InterpreterResizeInputTensor
TFL_NewInterpreter
TFL_NewInterpreterOptions
TFL_NewModel
TFL_NewModelFromFile
TFL_TensorByteSize
TFL_TensorCopyFromBuffer
TFL_TensorCopyToBuffer
TFL_TensorData
TFL_TensorDim
TFL_TensorName
TFL_TensorNumDims
TFL_TensorQuantizationParams
TFL_TensorType
TFL_Version

Symbols in the new DLL: none.

@mkustermann will make a new branch which we will pin in DEPS for now.

**Comment by mkustermann** [comment]
We will use 3c777c40608a2a9f1427bfe0028ab48e7116b4c1 for pulling in to dart-lang/sdk and g3.

**Comment by mkustermann** [comment]
@lambdabaa We don't know how the dll was built. Could you take a look at this?

**Comment by lambdabaa** [comment]
@mkustermann Is it okay to keep the tflite_native revision in the sdk `DEPS` at 0.2.2 https://github.com/dart-lang/sdk/commit/62ec3927680d9e614e70dbf7d1a8445a4a66b4f4#diff-946813de8d9b30857edae58aec4f3a7f for D26?

**Comment by mkustermann** [comment]
Yes, we'll just use an older version of the package, plus our ffi fixes for now. There's no reason to hurry with fixing the `dll` file.

**Comment by devoncarew** [comment]
@lambdabaa - was this addressed?
